name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  # pre-commit:
  #   name: Run pre-commit hooks
  #   runs-on: ubuntu-latest
  #   if: github.actor != 'github-classroom[bot]'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with: { python-version: "3.10" }
  #     - uses: pre-commit/action@v3.0.1
  run-autograding-tests:
    runs-on: ubuntu-latest
    # needs: pre-commit
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.10" }
    - uses: pre-commit/action@v3.0.1

    - name: A command test
      id: main-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: A command test
        setup-command: ""
        command: make test
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAIN-TEST_RESULTS: "${{ steps.main-test.outputs.result }}"
      with:
          runners: main-test
